<?php

namespace Siriru\GSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GoldsprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoldsprintRepository extends EntityRepository
{
}
